		xref	Commander_Init
		xref	Commander_Process
		xref	CmdMoveIL
		xref	CmdMoveIW
		xref	CmdMoveIB
		xref	CmdAddIL
		xref	CmdAddIW
		xref	CmdAddIB
		xref	CmdSubIL
		xref	CmdSubIW
		xref	CmdSubIB
		xref	CmdLerpWord